#:schema https://raw.githubusercontent.com/usecannon/cannon/refs/heads/dev/packages/lsp/src/schema.json
name = "cow-shed"
version = "2.0.0"

[var.main]
salt = "<%= HashZero %>"
composableCow = "<%= AddressZero %>"

[deploy.Shed]
artifact = "COWShed"
create2 = true
ifExists = "continue"
salt = "<%= settings.salt %>"

[deploy.ShedForComposableCoW]
artifact = "COWShedForComposableCoW"
create2 = true
ifExists = "continue"
salt = "<%= settings.salt %>"
args = ["<%= settings.composableCow %>"]

[deploy.Factory]
artifact = "COWShedFactory"
create2 = true
ifExists = "continue"
salt = "<%= settings.salt %>"
args = ["<%= contracts.Shed.address %>"]

[deploy.FactoryForComposableCoW]
artifact = "COWShedFactory"
create2 = true
ifExists = "continue"
salt = "<%= settings.salt %>"
args = ["<%= contracts.ShedForComposableCoW.address %>"]
