[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# The following options are here to get deterministic deployment addresses
# https://book.getfoundry.sh/guides/deterministic-deployments-using-create2#configuring-your-foundrytoml
solc = "0.8.30"
evm_version = "prague" # https://docs.soliditylang.org/en/latest/using-the-compiler.html#target-options
bytecode_hash = "none"
cbor_metadata = false

via_ir = true
optimizer_runs = 1_000_000

fs_permissions = [{ access = "write", path = "deploymentAddresses.json"}]

[fmt]
sort_imports = true
